### ISSUE TITLE
can't start natnet_ros2 lifecycle node

### ISSUE THREAD

**Issue by antbono** [L2S-lab/natnet_ros2#1]
Hello everyone!

I have just compiled and installed the package as described on the readme. I am using ubu 22.04 and ros humble.

Unfortunately I can't use the gui to start the streaming, some errors occurs 

`[INFO] [launch]: All log files can be found below /home/toto/.ros/log/2024-06-19-13-00-12-178692-asusb-26093
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [marker_poses_server-1]: process started with pid [26096]
[INFO] [helper_node_r2.py-2]: process started with pid [26098]
[helper_node_r2.py-2] WARNING: you should run this program as super-user.
[helper_node_r2.py-2] WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
[helper_node_r2.py-2] Traceback (most recent call last):
[helper_node_r2.py-2]   File "/home/toto/humble_ws/install/natnet_ros2/lib/natnet_ros2/helper_node_r2.py", line 175, in start
[helper_node_r2.py-2]     kill_subp()
[helper_node_r2.py-2]   File "/home/toto/humble_ws/install/natnet_ros2/lib/natnet_ros2/helper_node_r2.py", line 56, in kill_subp
[helper_node_r2.py-2]     subprocess.check_call(["pkill","_ros2_daemon"])
[helper_node_r2.py-2]   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
[helper_node_r2.py-2]     raise CalledProcessError(retcode, cmd)
[helper_node_r2.py-2] subprocess.CalledProcessError: Command '['pkill', '_ros2_daemon']' returned non-zero exit status 1.
`

then I tried with the straight launch file 'natnet_ros2.launch.py' and i get

`[ERROR] [launch]: Caught exception in launch (see debug for traceback): LifecycleNode.__init__() missing 1 required keyword-only argument: 'namespace'`

I had a look to the launch file but there is no parameters such namespace...

Any suggestion? Thanks

**Comment by aarsht7** [comment]
commit [4d26909](https://github.com/L2S-lab/natnet_ros2/commit/4d26909173f30e6d66d6c89c9fe90ba574a8429f) solves this issue.
Thanks for reporting!

**Comment by antbono** [comment]
Thank you for your reply!
