### ISSUE TITLE
Cannot build on Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by Everglow0214** [L2S-lab/natnet_ros2#3]
Hello. I tried to build the package on a Raspi but did not succeed. Here are the messages:
```
/usr/bin/ld: /home/ctrllab/xing_ws/src/natnet_ros2/deps/NatNetSDK/lib/libNatNet.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/natnet_ros2_node.dir/build.make:215: natnet_ros2_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:546: CMakeFiles/natnet_ros2_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:146: all] Error 2
```
I checked [https://optitrack.com/support/downloads/developer-tools.html](https://optitrack.com/support/downloads/developer-tools.html).
It seems that a package for ARM-based devices is not provided...

**Comment by aarsht7** [comment]
Yes `libNatNet.so` is not compatible with ARM-based devices.
